In [1]:
import pandas as pd

root_path = "/home/julian/programming/cloned_repos/repos_for_master_thesis/d3rlpy/data/"
mimic_df = pd.read_csv(root_path +'mimic_dataset.csv')
# fix extubated:

mimic_df.loc[mimic_df["extubated"].isna(),"extubated"] = 0

In [2]:
mimic_df.head()

,bloc,icustayid,timestep,gender,age,elixhauser,re_admission,died_in_hosp,died_within_48h_of_out_time,morta_90,...,input_step,output_total,output_step,cumulated_balance,median_dose_vaso,max_dose_vaso,Shock_Index,PaO2_FiO2,SOFA,SIRS
0,1,30000153,6461550000,0,61,1,False,0,False,0,...,0.0,2180.0,0.0,2954.69,0.0,0.0,0.876050,58.3333,5,4
1,3,30000153,6461578800,0,61,1,False,0,False,0,...,0.0,2180.0,0.0,2954.69,0.0,0.0,0.621849,630.0000,6,2
2,1,30000484,5239600000,0,92,4,True,0,False,1,...,0.0,0.0,0.0,0.00,0.0,0.0,0.885956,58.3333,9,4
3,2,30000484,5239614400,0,92,4,True,0,False,1,...,0.0,260.0,260.0,-260.00,0.0,0.0,1.032180,125.0000,6,4
4,3,30000484,5239628800,0,92,4,True,0,False,1,...,750.0,360.0,100.0,390.00,0.0,0.0,0.912393,58.3333,8,2

In [3]:
#summary statistics of mimic dataset
mimic_df.describe()

,bloc,icustayid,timestep,gender,age,elixhauser,died_in_hosp,morta_90,delay_end_of_record_and_discharge_or_death,Height_cm,...,input_step,output_total,output_step,cumulated_balance,median_dose_vaso,max_dose_vaso,Shock_Index,PaO2_FiO2,SOFA,SIRS
count,475530.000000,4.755300e+05,4.755300e+05,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,...,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000
mean,7.474100,3.496878e+07,5.812920e+09,0.437781,65.385252,5.057016,0.175453,0.278563,260.779202,115.520924,...,252.620690,3315.404519,273.207352,1440.515605,0.041415,0.071682,0.760639,356.060265,5.066820,1.538725
std,4.770875,2.885789e+06,7.515278e+08,0.496114,16.257752,2.363921,0.380354,0.448292,343.669321,52.020625,...,484.881172,6935.869605,1327.952032,7671.726254,0.159753,1.085591,0.210332,353.564633,2.965434,1.012735
min,1.000000,3.000015e+07,4.418920e+09,0.000000,18.000000,0.000000,0.000000,0.000000,-85.444400,0.000000,...,0.000000,-1000.000000,-600.000000,-880258.000000,0.000000,0.000000,0.000000,-152.381000,0.000000,0.000000
25%,3.000000,3.248238e+07,5.193929e+09,0.000000,56.000000,3.000000,0.000000,0.000000,72.433300,66.000000,...,0.000000,540.000000,0.000000,-828.951250,0.000000,0.000000,0.611979,149.368000,3.000000,1.000000
50%,7.000000,3.494062e+07,5.805484e+09,0.000000,67.000000,5.000000,0.000000,0.000000,153.000000,74.000000,...,52.584750,1685.000000,180.000000,534.000000,0.000000,0.000000,0.734109,235.714000,5.000000,2.000000
75%,11.000000,3.747037e+07,6.440029e+09,1.000000,78.000000,7.000000,0.000000,1.000000,322.139000,168.000000,...,301.415000,3779.000000,375.000000,3465.557500,0.000000,0.000000,0.879177,399.329750,7.000000,2.000000
max,20.000000,3.999986e+07,7.717548e+09,1.000000,103.000000,15.000000,1.000000,1.000000,9717.390000,1295.000000,...,18168.300000,881057.000000,876937.000000,142142.000000,25.397000,375.000000,11.946400,2828.570000,20.000000,4.000000

In [4]:
with open('mimic_df_columns.txt', 'w') as f:
    for col in mimic_df.columns:
        f.write(f"{col}\n")

In [5]:
sepsis_cohort = pd.read_csv(root_path +'sepsis_cohort.csv')

In [6]:
sepsis_cohort.head()

   icustayid  morta_90  max_SOFA  max_SIRS    onset_time
0   30000153         0         5         4  6.461550e+09
1   30000484         1        10         3  5.239630e+09
2   30000646         1         6         3  7.079390e+09
3   30000831         0         9         3  5.374050e+09
4   30001148         0         4         1  5.890640e+09

In [7]:
sepsis_cohort.describe()

          icustayid      morta_90      max_SOFA      max_SIRS    onset_time
count  4.576100e+04  45761.000000  45761.000000  45761.000000  4.576100e+04
mean   3.496576e+07      0.253163      6.804681      2.171369  5.816476e+09
std    2.912470e+06      0.434828      2.901148      1.027805  7.530943e+08
min    3.000015e+07      0.000000      2.000000      0.000000  4.418930e+09
25%    3.243510e+07      0.000000      5.000000      2.000000  5.196000e+09
50%    3.490493e+07      0.000000      6.000000      2.000000  5.809700e+09
75%    3.748518e+07      1.000000      8.000000      3.000000  6.447120e+09
max    3.999986e+07      1.000000     20.000000      4.000000  7.717370e+09

In [8]:
import numpy as np
import pandas as pd

def compute_sofa_scores(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    # Respiratory (paO2 / FiO2)
    df["paO2_FiO2"] = df["paO2"] / df["FiO2_1"]
    df["SOFA_resp"] = pd.cut(
        df["paO2_FiO2"],
        bins=[-np.inf, 100, 200, 300, 400, np.inf],
        labels=[4, 3, 2, 1, 0]
    ).astype("float")

    # Coagulation (Platelets)
    df["SOFA_coag"] = pd.cut(
        df["Platelets_count"],
        bins=[-np.inf, 20, 50, 100, 150, np.inf],
        labels=[4, 3, 2, 1, 0]
    ).astype("float")

    # Liver (Bilirubin)
    df["SOFA_liver"] = pd.cut(
        df["Total_bili"],
        bins=[-np.inf, 1.2, 2.0, 6.0, 12.0, np.inf],
        labels=[0, 1, 2, 3, 4]
    ).astype("float")

    # Cardiovascular (MAP or vasopressors proxy)
    conditions = [
        (df["max_dose_vaso"] > 0.1),
        (df["max_dose_vaso"] > 0),
        (df["MeanBP"] < 65),
        (df["MeanBP"] < 70)
    ]
    choices = [4, 3, 2, 1]
    df["SOFA_cardio"] = np.select(conditions, choices, default=0).astype("float")


    # CNS (GCS)
    df["SOFA_cns"] = pd.cut(
        df["GCS"],
        bins=[-np.inf, 5, 9, 12, 14, 15],
        labels=[4, 3, 2, 1, 0],
        include_lowest=True
    ).astype("float")

    # Renal (Creatinine or Urine Output)
    df["SOFA_renal"] = pd.cut(
        df["Creatinine"],
        bins=[-np.inf, 1.2, 2.0, 3.5, 5.0, np.inf],
        labels=[0, 1, 2, 3, 4]
    ).astype("float")

    # Total SOFA
    sofa_cols = [
        "SOFA_resp", "SOFA_coag", "SOFA_liver",
        "SOFA_cardio", "SOFA_cns", "SOFA_renal"
    ]
    df["SOFA_total"] = df[sofa_cols].sum(axis=1, skipna=False)

    return df

mimic_df = compute_sofa_scores(mimic_df)

In [9]:
import numpy as np
import pandas as pd


def compute_sofa_scores(
    df: pd.DataFrame,
    timestep_resolution: float = 4.0,          # hours between successive rows
) -> pd.DataFrame:
    """
    SOFA score implementation that mirrors the NumPy logic used by the team.
    Requires the following columns (case-sensitive):
        paO2, FiO2_1, Platelets_count, Total_bili,
        MeanBP, max_dose_vaso, GCS, Creatinine, output_step
    """
    df = df.copy()

    # ───────────────────────── Respiratory ──────────────────────────
    df["paO2_FiO2"] = df["paO2"] / df["FiO2_1"]
    pfi = df["paO2_FiO2"]
    df["SOFA_resp"] = np.select(
        [pfi > 400,
         (pfi >= 300) & (pfi < 400),
         (pfi >= 200) & (pfi < 300),
         (pfi >= 100) & (pfi < 200)],
        [0, 1, 2, 3],
        default=4
    ).astype(float)

    # ──────────────────────── Coagulation ───────────────────────────
    pl = df["Platelets_count"]
    df["SOFA_coag"] = np.select(
        [pl > 150,
         (pl >= 100) & (pl < 150),
         (pl >= 50)  & (pl < 100),
         (pl >= 20)  & (pl < 50)],
        [0, 1, 2, 3],
        default=4
    ).astype(float)

    # ────────────────────────── Liver ───────────────────────────────
    bili = df["Total_bili"]
    df["SOFA_liver"] = np.select(
        [bili < 1.2,
         (bili >= 1.2) & (bili < 2.0),
         (bili >= 2.0) & (bili < 6.0),
         (bili >= 6.0) & (bili < 12.0)],
        [0, 1, 2, 3],
        default=4
    ).astype(float)

    # ────────────────────── Cardiovascular ──────────────────────────
    map_  = df["MeanBP"]
    vaso  = df["max_dose_vaso"]
    df["SOFA_cardio"] = np.select(
        [map_ >= 70,
         (map_ < 70) & (map_ >= 65),
         map_ < 65,
         (vaso > 0)  & (vaso <= 0.1),
         vaso > 0.1],
        [0, 1, 2, 3, 4]
    ).astype(float)

    # ─────────────────────────── CNS ────────────────────────────────
    gcs = df["GCS"]
    df["SOFA_cns"] = np.select(
        [gcs > 14,
         (gcs > 12) & (gcs <= 14),
         (gcs >  9) & (gcs <= 12),
         (gcs >  5) & (gcs <=  9)],
        [0, 1, 2, 3],
        default=4
    ).astype(float)

    # ────────────────────────── Renal ───────────────────────────────
    cr   = df["Creatinine"]
    uo   = df["output_step"]                        # mL in this timestep
    thr3 = 500 * timestep_resolution / 24          # e.g. 83.33 mL for 4-hour step
    thr4 = 200 * timestep_resolution / 24          # e.g. 33.33 mL for 4-hour step

    df["SOFA_renal"] = np.select(
        [cr < 1.2,
         (cr >= 1.2) & (cr < 2.0),
         (cr >= 2.0) & (cr < 3.5),
         ((cr >= 3.5) & (cr < 5.0)) | (uo < thr3),
         (cr > 5.0)               | (uo < thr4)],
        [0, 1, 2, 3, 4]
    ).astype(float)

    # ──────────────────────── Total score ───────────────────────────
    sofa_cols = [
        "SOFA_resp", "SOFA_coag", "SOFA_liver",
        "SOFA_cardio", "SOFA_cns", "SOFA_renal"
    ]
    df["SOFA_total"] = df[sofa_cols].sum(axis=1, skipna=False)

    return df
mimic_df = compute_sofa_scores(mimic_df)

In [10]:
mimic_df.describe()

,bloc,icustayid,timestep,gender,age,elixhauser,died_in_hosp,morta_90,delay_end_of_record_and_discharge_or_death,Height_cm,...,SOFA,SIRS,paO2_FiO2,SOFA_resp,SOFA_coag,SOFA_liver,SOFA_cardio,SOFA_cns,SOFA_renal,SOFA_total
count,475530.000000,4.755300e+05,4.755300e+05,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,...,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000
mean,7.474100,3.496878e+07,5.812920e+09,0.437781,65.385252,5.057016,0.175453,0.278563,260.779202,115.520924,...,5.066820,1.538725,356.060267,1.880455,0.591836,0.680201,0.421883,0.827702,0.685486,5.087563
std,4.770875,2.885789e+06,7.515278e+08,0.496114,16.257752,2.363921,0.380354,0.448292,343.669321,52.020625,...,2.965434,1.012735,353.564624,1.348745,0.911245,1.156220,0.723631,1.222853,0.983237,2.972864
min,1.000000,3.000015e+07,4.418920e+09,0.000000,18.000000,0.000000,0.000000,0.000000,-85.444400,0.000000,...,0.000000,0.000000,-152.380952,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,3.248238e+07,5.193929e+09,0.000000,56.000000,3.000000,0.000000,0.000000,72.433300,66.000000,...,3.000000,1.000000,149.367975,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
50%,7.000000,3.494062e+07,5.805484e+09,0.000000,67.000000,5.000000,0.000000,0.000000,153.000000,74.000000,...,5.000000,2.000000,235.714286,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000
75%,11.000000,3.747037e+07,6.440029e+09,1.000000,78.000000,7.000000,0.000000,1.000000,322.139000,168.000000,...,7.000000,2.000000,399.330068,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000
max,20.000000,3.999986e+07,7.717548e+09,1.000000,103.000000,15.000000,1.000000,1.000000,9717.390000,1295.000000,...,20.000000,4.000000,2828.571429,4.000000,4.000000,4.000000,2.000000,4.000000,4.000000,20.000000

In [11]:
mimic_df[mimic_df["SOFA"]==20]

,bloc,icustayid,timestep,gender,age,elixhauser,re_admission,died_in_hosp,died_within_48h_of_out_time,morta_90,...,SOFA,SIRS,paO2_FiO2,SOFA_resp,SOFA_coag,SOFA_liver,SOFA_cardio,SOFA_cns,SOFA_renal,SOFA_total
189513,15,33933739,6002881600,0,58,6,False,1,True,1,...,20,2,190.0000,3.0,4.0,4.0,2.0,4.0,3.0,20.0
235203,9,34886673,4573245200,0,52,4,False,1,True,1,...,20,2,81.0000,4.0,4.0,4.0,2.0,4.0,2.0,20.0
235204,10,34886673,4573259600,0,52,4,False,1,True,1,...,20,2,75.8421,4.0,4.0,4.0,2.0,4.0,2.0,20.0
235205,11,34886673,4573274000,0,52,4,False,1,True,1,...,20,2,65.0000,4.0,4.0,4.0,2.0,4.0,2.0,20.0
235206,12,34886673,4573288400,0,52,4,False,1,True,1,...,20,2,65.0000,4.0,4.0,4.0,2.0,4.0,2.0,20.0

In [12]:
mimic_df[mimic_df["SOFA_total"]==23]

Empty DataFrame
Columns: [bloc, icustayid, timestep, gender, age, elixhauser, re_admission, died_in_hosp, died_within_48h_of_out_time, morta_90, delay_end_of_record_and_discharge_or_death, Height_cm, Weight_kg, GCS, RASS, HR, SysBP, MeanBP, DiaBP, RR, SpO2, Temp_C, Temp_F, CVP, PAPsys, PAPmean, PAPdia, CI, SVR, Interface, FiO2_100, FiO2_1, O2flow, PEEP, TidalVolume, MinuteVentil, PAWmean, PAWpeak, PAWplateau, Respiratory_Rate, Ultrafiltrate_Output, Blood_Flow, Potassium, Sodium, Chloride, Glucose, BUN, Creatinine, Magnesium, Calcium, Ionised_Ca, CO2_mEqL, SGOT, SGPT, Total_bili, Direct_bili, Total_protein, Albumin, Troponin, CRP, Hb, Ht, RBC_count, WBC_count, Platelets_count, PTT, PT, ACT, INR, Arterial_pH, paO2, paCO2, Arterial_BE, Arterial_lactate, HCO3, ETCO2, SvO2, Anion_Gap, Ammonia, Fibrinogen, Absolute_Neutrophil_Count, Phosphorous, SaO2, Triglyceride, ScvO2, LDH, CK_MB, BNP, Iron, Thyroid_Stimulating_Hormone, Creatinine_Urine, Potassium_Urine, Sodium_Urine, Urea_Nitrogen_Urine, Creatinine_Clearance, T3, Gamma_Glutamyltransferase, Myoglobin, Heparin_LMW, Osmolality_Urine, ...]
Index: []

[0 rows x 133 columns]

In [13]:
mimic_df[mimic_df["SOFA_total"]>=2]["median_dose_vaso"].describe()

count    426895.000000
mean          0.044476
std           0.162127
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max          25.397000
Name: median_dose_vaso, dtype: float64

In [14]:
mimic_df[mimic_df["SOFA"]>=2]["median_dose_vaso"].describe()

count    426508.000000
mean          0.044502
std           0.162184
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max          25.397000
Name: median_dose_vaso, dtype: float64

In [15]:
mimic_df[mimic_df["SOFA"]>=2]["input_step"].describe()

count    426508.000000
mean        260.268621
std         496.453714
min           0.000000
25%           0.000000
50%          58.514050
75%         309.804000
max       18168.300000
Name: input_step, dtype: float64

In [16]:
mimic_df.describe()

,bloc,icustayid,timestep,gender,age,elixhauser,died_in_hosp,morta_90,delay_end_of_record_and_discharge_or_death,Height_cm,...,SOFA,SIRS,paO2_FiO2,SOFA_resp,SOFA_coag,SOFA_liver,SOFA_cardio,SOFA_cns,SOFA_renal,SOFA_total
count,475530.000000,4.755300e+05,4.755300e+05,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,...,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000,475530.000000
mean,7.474100,3.496878e+07,5.812920e+09,0.437781,65.385252,5.057016,0.175453,0.278563,260.779202,115.520924,...,5.066820,1.538725,356.060267,1.880455,0.591836,0.680201,0.421883,0.827702,0.685486,5.087563
std,4.770875,2.885789e+06,7.515278e+08,0.496114,16.257752,2.363921,0.380354,0.448292,343.669321,52.020625,...,2.965434,1.012735,353.564624,1.348745,0.911245,1.156220,0.723631,1.222853,0.983237,2.972864
min,1.000000,3.000015e+07,4.418920e+09,0.000000,18.000000,0.000000,0.000000,0.000000,-85.444400,0.000000,...,0.000000,0.000000,-152.380952,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,3.248238e+07,5.193929e+09,0.000000,56.000000,3.000000,0.000000,0.000000,72.433300,66.000000,...,3.000000,1.000000,149.367975,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
50%,7.000000,3.494062e+07,5.805484e+09,0.000000,67.000000,5.000000,0.000000,0.000000,153.000000,74.000000,...,5.000000,2.000000,235.714286,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000
75%,11.000000,3.747037e+07,6.440029e+09,1.000000,78.000000,7.000000,0.000000,1.000000,322.139000,168.000000,...,7.000000,2.000000,399.330068,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000
max,20.000000,3.999986e+07,7.717548e+09,1.000000,103.000000,15.000000,1.000000,1.000000,9717.390000,1295.000000,...,20.000000,4.000000,2828.571429,4.000000,4.000000,4.000000,2.000000,4.000000,4.000000,20.000000

In [17]:
observation_columns = [
    # Time-varying
    "GCS", "HR", "SysBP", "DiaBP", "MeanBP", "RR", "Temp_C",
    "FiO2_100", "FiO2_1", "Potassium", "Sodium", "Chloride", "Glucose",
    "INR", "Magnesium", "Calcium", "Hb", "WBC_count", "Platelets_count",
    "PTT", "PT", "Arterial_pH", "Arterial_lactate", "paO2", "paCO2",
    "PaO2_FiO2", "HCO3", "SpO2", "BUN", "Creatinine", "SGOT",
    "SGPT", "Total_bili", "Arterial_BE",

    # derived or sofa scores:

    "paO2_FiO2","SOFA_resp", "SOFA_coag", "SOFA_liver", "SOFA_cardio", "SOFA_cns", "SOFA_renal",
    #"SOFA_total", # used in dense reward

    # Demographics
    "age", "gender", "Weight_kg", "mechvent", "extubated", "re_admission",
    # id
    "icustayid"
]

states = mimic_df[observation_columns]

states

,GCS,HR,SysBP,DiaBP,MeanBP,RR,Temp_C,FiO2_100,FiO2_1,Potassium,...,SOFA_cardio,SOFA_cns,SOFA_renal,age,gender,Weight_kg,mechvent,extubated,re_admission,icustayid
0,15.0,104.2500,119.000,59.0000,79.0000,20.5000,35.5556,36.0000,0.36,5.40000,...,0.0,0.0,1.0,61,0,68.5,0,0.0,False,30000153
1,11.0,74.0000,119.000,59.0000,79.0000,21.6923,37.8143,46.6667,0.40,4.60000,...,0.0,2.0,0.0,61,0,70.1,0,0.0,False,30000153
2,15.0,104.8750,118.375,71.0000,81.0000,20.5000,35.5556,36.0000,0.36,3.90000,...,0.0,0.0,0.0,92,0,68.5,0,0.0,True,30000484
3,14.0,104.2500,101.000,71.0000,81.0000,20.5000,35.5556,36.0000,0.36,4.40000,...,0.0,1.0,1.0,92,0,68.5,0,0.0,True,30000484
4,15.0,85.4000,93.600,41.5500,58.9000,14.3000,35.5556,36.0000,0.36,4.40000,...,2.0,0.0,1.0,92,0,68.5,0,0.0,True,30000484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475525,15.0,78.4545,103.333,19.8333,53.2273,13.9091,37.6692,40.0000,0.40,4.51538,...,2.0,0.0,0.0,49,0,68.0,0,0.0,False,39999230
475526,15.0,78.4545,103.333,19.8333,53.2273,13.9091,37.6692,40.0000,0.40,4.51538,...,2.0,0.0,0.0,49,0,68.0,0,0.0,False,39999230
475527,15.0,78.4545,103.333,19.8333,53.2273,13.9091,37.6692,40.0000,0.40,4.51538,...,2.0,0.0,0.0,49,0,68.0,0,0.0,False,39999230
475528,15.0,78.4545,103.333,19.8333,53.2273,13.9091,37.6692,40.0000,0.40,4.51538,...,2.0,0.0,0.0,54,0,68.0,0,0.0,False,39999286
475529,15.0,78.4545,103.333,19.8333,53.2273,13.9091,37.6692,40.0000,0.40,4.51538,...,2.0,0.0,0.0,62,0,68.0,0,0.0,False,39999858

In [18]:
mimic_df[["median_dose_vaso","max_dose_vaso"]].describe()

       median_dose_vaso  max_dose_vaso
count     475530.000000  475530.000000
mean           0.041415       0.071682
std            0.159753       1.085591
min            0.000000       0.000000
25%            0.000000       0.000000
50%            0.000000       0.000000
75%            0.000000       0.000000
max           25.397000     375.000000

In [19]:
mimic_df[["input_total","input_step"]].describe()

         input_total     input_step
count  475530.000000  475530.000000
mean     4755.920121     252.620690
std      6652.596164     484.881172
min         0.000000       0.000000
25%       462.521000       0.000000
50%      2759.210000      52.584750
75%      6533.527500     301.415000
max    156663.000000   18168.300000

In [20]:
mimic_df[["morta_90","died_within_48h_of_out_time","died_in_hosp","delay_end_of_record_and_discharge_or_death"]].describe()

,morta_90,died_in_hosp,delay_end_of_record_and_discharge_or_death
count,475530.000000,475530.000000,475530.000000
mean,0.278563,0.175453,260.779202
std,0.448292,0.380354,343.669321
min,0.000000,0.000000,-85.444400
25%,0.000000,0.000000,72.433300
50%,0.000000,0.000000,153.000000
75%,1.000000,0.000000,322.139000
max,1.000000,1.000000,9717.390000

In [21]:
mimic_df["delay_end_of_record_and_discharge_or_death"]

0         257.289
1         257.289
2         182.444
3         182.444
4         182.444
           ...
475525    749.628
475526    749.628
475527    749.628
475528    288.722
475529    150.750
Name: delay_end_of_record_and_discharge_or_death, Length: 475530, dtype: float64

In [22]:
mimic_df[mimic_df["input_step"]>0][["input_step","median_dose_vaso"]].describe()

          input_step  median_dose_vaso
count  324964.000000     324964.000000
mean      369.667769          0.059613
std       548.429698          0.187214
min         0.002967          0.000000
25%        47.640300          0.000000
50%       180.000000          0.000000
75%       465.469250          0.035000
max     18168.300000         25.397000

In [23]:
mimic_df[mimic_df["median_dose_vaso"]>0][["input_step","median_dose_vaso"]].describe()

         input_step  median_dose_vaso
count  93623.000000      93623.000000
mean     554.663920          0.210357
std      765.189668          0.306738
min        0.000000          0.001000
25%      100.000000          0.060000
50%      271.449000          0.135000
75%      701.507500          0.250000
max    18168.300000         25.397000

In [24]:
for i,icustay_id in enumerate(sepsis_cohort["icustayid"]):
    print(icustay_id)
    print(sepsis_cohort[sepsis_cohort["icustayid"]==icustay_id]["onset_time"])
    print(mimic_df[mimic_df["icustayid"]==icustay_id]["timestep"].mean())
    if i >10:
        break

30000153
0    6.461550e+09
Name: onset_time, dtype: float64
6461564400.0
30000484
1    5.239630e+09
Name: onset_time, dtype: float64
5239708000.0
30000646
2    7.079390e+09
Name: onset_time, dtype: float64
7079354800.0
30000831
3    5.374050e+09
Name: onset_time, dtype: float64
5374103200.0
30001148
4    5.890640e+09
Name: onset_time, dtype: float64
5890580400.0
30001446
5    6.825100e+09
Name: onset_time, dtype: float64
6825164800.0
30001555
6    6.554160e+09
Name: onset_time, dtype: float64
6554246400.0
30002012
7    6.492500e+09
Name: onset_time, dtype: float64
6492545600.0
30002498
8    5.934710e+09
Name: onset_time, dtype: float64
5934733200.0
30002654
9    5.831580e+09
Name: onset_time, dtype: float64
5831660800.0
30002925
10    5.188760e+09
Name: onset_time, dtype: float64
5188788800.0
30003130
11    5.840070e+09
Name: onset_time, dtype: float64
5840160000.0

In [25]:
states.drop("extubated",axis=1).isna().sum().sum()

0

In [26]:
states["extubated"].count()/states["extubated"].isna().sum()

/tmp/ipykernel_2229/3706797726.py:1: RuntimeWarning: divide by zero encountered in scalar divide
  states["extubated"].count()/states["extubated"].isna().sum()

inf

In [27]:
states["extubated"].describe()

count    475530.000000
mean          0.026115
std           0.152021
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: extubated, dtype: float64

In [28]:
mimic_df[["median_dose_vaso","input_step"]].isna().sum()

median_dose_vaso    0
input_step          0
dtype: int64

In [29]:

# import numpy as np
# import pickle
# from d3rlpy.dataset.components import Episode  # Ensure this imports the default Episode class
# from d3rlpy.dataset import ReplayBuffer, FIFOBuffer

# def transform_dataset_to_Replaybuffer(dataset):

#     for icustay_id in sepsis_cohort["icustayid"]:
#         # Assume each ep is a dict with keys as shown in your printout.
#         observations = ep["observations"]
#         actions = ep["actions"]
#         rewards = ep["rewards"]
#         terminals = ep["terminals"]
#         if isinstance(terminals, (list, np.ndarray)):
#             terminated = bool(terminals[-1])
#         else:
#             terminated = bool(terminals)
#         # Optionally, next_observations is available as well.
#         next_observations = ep.get("next_observations", None)
        
#         # Create an Episode object.
#         # The Episode class in d3rlpy typically accepts these arrays directly.
#         episode = Episode(
#             observations=observations,
#             actions=actions,
#             rewards=rewards,
#             terminated=terminated,
#         )
#         converted_episodes.append(episode)
#     buffer_impl = FIFOBuffer(limit=1000000)
#     replay_buffer = ReplayBuffer(buffer=buffer_impl, episodes=episodes)
#     return converted_episodes

In [30]:
sepsis_cohort.describe()

          icustayid      morta_90      max_SOFA      max_SIRS    onset_time
count  4.576100e+04  45761.000000  45761.000000  45761.000000  4.576100e+04
mean   3.496576e+07      0.253163      6.804681      2.171369  5.816476e+09
std    2.912470e+06      0.434828      2.901148      1.027805  7.530943e+08
min    3.000015e+07      0.000000      2.000000      0.000000  4.418930e+09
25%    3.243510e+07      0.000000      5.000000      2.000000  5.196000e+09
50%    3.490493e+07      0.000000      6.000000      2.000000  5.809700e+09
75%    3.748518e+07      1.000000      8.000000      3.000000  6.447120e+09
max    3.999986e+07      1.000000     20.000000      4.000000  7.717370e+09

In [31]:
sepsis_icu_ids = sepsis_cohort["icustayid"].unique()
sepsis_df = mimic_df[mimic_df["icustayid"].isin(sepsis_icu_ids)].copy()
print(sepsis_df.shape)
print(mimic_df.shape)

(452670, 133)
(475530, 133)

In [ ]:
# import numpy as np
# import pandas as pd

# # --- prerequisites ---------------------------------------------------------
# # df must contain at least:  icustayid, charttime  (as pandas.Timestamp)
# # If 'charttime' is still a string, do: df['charttime'] = pd.to_datetime(df['charttime'])

# # --- 1. sort and make Δt ----------------------------------------------------
# def calculate_deltas(df: pd.DataFrame):
#   df = df.sort_values(['icustayid', 'timestep'])
#   df["timestep_dt"] = pd.to_datetime(df['timestep'], unit='s', utc=True)

#   df['delta_hours'] = (
#       df.groupby('icustayid')['timestep_dt']
#         .diff()                      # timedeltas per stay
#         .dt.total_seconds()
#         .div(3600)                   # → hours (float)
#   )

#   # first row of every stay has NaN; drop if you only care about intervals
#   deltas = df['delta_hours'].dropna()

#   # --- 2. quick sanity-checks -------------------------------------------------
#   print("unique step sizes (h):", sorted(deltas.unique())[:10], "…")
#   print(deltas.describe())           # min/median/max, std, …

#   # how often did we deviate from 4 h?
#   off_grid = deltas[deltas != 4]
#   print(f"Pct of non-4h steps: {100*len(off_grid)/len(deltas):.1f}%")

#   # bucketised counts you can plot later
#   step_hist = deltas.value_counts().sort_index()
#   return step_hist

# sepsis_hist = calculate_deltas(sepsis_df)
# mimic_hist = calculate_deltas(mimic_df)

unique step sizes (h): [4.0, 8.0, 12.0, 16.0, 20.0, 24.0, 28.0, 32.0, 36.0, 40.0] …
count    406938.000000
mean          4.565226
std           3.452828
min           4.000000
25%           4.000000
50%           4.000000
75%           4.000000
max          76.000000
Name: delta_hours, dtype: float64
Pct of non-4h steps: 4.2%
unique step sizes (h): [4.0, 8.0, 12.0, 16.0, 20.0, 24.0, 28.0, 32.0, 36.0, 40.0] …
count    425937.000000
mean          4.579560
std           3.502162
min           4.000000
25%           4.000000
50%           4.000000
75%           4.000000
max          76.000000
Name: delta_hours, dtype: float64
Pct of non-4h steps: 4.3%

In [33]:
# import pandas as pd
# import numpy as np

# def pad_to_regular_grid(df: pd.DataFrame,
#                         freq: str = "4H",
#                         id_col: str = "icustayid",
#                         time_col: str = "timestep_dt",
#                         action_cols: list[str] = None,
#                         ffill_cols: list[str] = None,
#                         reward_col: str | None = None) -> pd.DataFrame:
#     """
#     Re-index each ICU stay onto a fixed grid and create 'is_padding' flag.

#     Parameters
#     ----------
#     df : long table with at least [id_col, time_col]
#     freq : Pandas offset alias, e.g. '4H', '1H'
#     action_cols : columns that should become 0 when padded
#     ffill_cols : columns to forward-fill (typically vitals/labs)
#     reward_col : set to 0 on padded rows (leave None to skip)

#     Returns
#     -------
#     Same shape as input *plus* padded rows, sorted by [id_col, time_col].
#     """
#     action_cols = action_cols or []
#     ffill_cols  = ffill_cols  or []

#     # ensure timestamp index for reindexing
#     df = df.sort_values([id_col, time_col])

#     def _pad(stay):
#         stay = stay.set_index(time_col)
#         full_idx = pd.date_range(stay.index.min(),
#                                  stay.index.max(),
#                                  freq=freq,
#                                  name=time_col)
#         stay = stay.reindex(full_idx)  # NaNs where nothing happened

#         stay["is_padding"] = stay[id_col].isna()   # True on synthetic rows
#         stay[id_col] = stay[id_col].ffill()        # restore key

#         # forward-fill state variables
#         if ffill_cols:
#             stay[ffill_cols] = stay[ffill_cols].ffill()

#         # zero-out actions on padded rows
#         for c in action_cols:
#             stay.loc[stay["is_padding"], c] = 0

#         # zero reward on padded rows
#         if reward_col:
#             stay.loc[stay["is_padding"], reward_col] = 0.0

#         # you can also store elapsed time since last *real* obs
#         stay["delta_hours"] = stay.index.to_series().diff().dt.total_seconds().div(3600)

#         return stay.reset_index()

#     out = (df.groupby(id_col, group_keys=False)
#              .apply(_pad)
#              .reset_index(drop=True)
#              .sort_values([id_col, time_col]))

#     return out

In [34]:
# sepsis_df["timestep_dt"] = pd.to_datetime(sepsis_df['timestep'], unit='s', utc=True)


# action_cols = ["output_total","output_step", "median_dose_vaso", "max_dose_vaso"]
# filtered_sepsis_df = sepsis_df[observation_columns+action_cols+["SOFA","timestep_dt","timestep"]].copy()
# sepsis_padded = pad_to_regular_grid(
#     filtered_sepsis_df,
#     freq="4h",
#     action_cols=action_cols,
#     ffill_cols=observation_columns,
# )

In [35]:
# sepsis_padded_hist = calculate_deltas(sepsis_padded)

In [36]:
# deltas = (sepsis_padded
#           .groupby("icustayid")["timestep_dt"]
#           .diff()
#           .dt.total_seconds()
#           .div(3600)
#           .dropna())

# print("Still off-grid? ->", (deltas != 4).any())
sepsis_df["timestep_dt"] = pd.to_datetime(sepsis_df['timestep'], unit='s', utc=True)
deltas = (sepsis_df
          .groupby("icustayid")["timestep_dt"]
          .diff()
          .dt.total_seconds()
          .div(3600)
          .dropna())

print("Still off-grid? ->", (deltas != 4).any())

Still off-grid? -> True

In [37]:
# sepsis_padded.head()

In [ ]:
import pandas as pd
import numpy as np

def pad_fast(df: pd.DataFrame,
             freq: str = "4h",
             id_col: str = "icustayid",
             time_col: str = "timestep_dt",
             action_cols: list[str] | None = None,
             ffill_cols:  list[str] | None = None,
             reward_col:  str | None = None) -> pd.DataFrame:
    """
    Vectorised, ~10× faster version of pad_to_regular_grid.
    Requires pandas ≥ 2.3 (for GroupBy.resample).
    """
    action_cols = action_cols or []
    ffill_cols  = ffill_cols  or []

    df = df.copy()
    df["_orig"] = 1                    # sentinel to spot real rows
    df = df.sort_values([id_col, time_col]).set_index(time_col)

    # --- 1. build the regular grid & mark synthetic rows --------------------
    padded = (df
              .groupby(id_col)         # stays stay separate, C-level loop
              .resample(freq)          # up-sample index (adds NaNs)
              .first()                 # keep existing rows where they exist
    )
    padded["is_padding"] = padded["_orig"].isna()

    # --- 2. restore keys & fill state --------------------------------------
    padded[id_col] = padded[id_col].ffill()  # cheap because already sorted
    if ffill_cols:
        padded[ffill_cols] = padded[ffill_cols].ffill().infer_objects(copy=False)

    for c in action_cols:                        # zero-out actions on gaps
        padded.loc[padded["is_padding"], c] = 0

    if reward_col:
        padded.loc[padded["is_padding"], reward_col] = 0.0

    # elapsed time since previous step (optional but often handy)
    idx_time = padded.index.get_level_values(time_col)
    padded["delta_hours"] = (
        idx_time
        .to_series(index=padded.index)           # align with MultiIndex
        .groupby(padded[id_col]).diff()
        .dt.total_seconds().div(3600)
    )

    # --- 3. flatten MultiIndex & tidy up -----------------------------------
    padded = (padded
              .reset_index(level=1)             # drop the resample level
              .rename(columns={time_col: time_col})
              .reset_index(drop=True)
              .drop(columns="_orig")
              .sort_values([id_col, time_col])
    )
    return padded

In [39]:

sepsis_df["timestep_dt"] = pd.to_datetime(sepsis_df['timestep'], unit='s', utc=True)


action_cols = ["output_total","output_step", "median_dose_vaso", "max_dose_vaso"]
filtered_sepsis_df = sepsis_df[observation_columns+action_cols+["SOFA","timestep_dt","timestep"]].copy()
sepsis_fast_padded = pad_fast(
    filtered_sepsis_df,
    freq="4h",
    action_cols=action_cols,
    ffill_cols=observation_columns,
)

/tmp/ipykernel_2229/1796815513.py:26: FutureWarning: DataFrameGroupBy.resample operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .first()                 # keep existing rows where they exist

In [40]:
deltas = (sepsis_fast_padded
          .groupby("icustayid")["timestep_dt"]
          .diff()
          .dt.total_seconds()
          .div(3600)
          .dropna())

print("Still off-grid? ->", (deltas != 4).any())

Still off-grid? -> False

In [41]:
import numpy as np
import pandas as pd
from d3rlpy.dataset import Episode, ReplayBuffer, FIFOBuffer 
from d3rlpy.constants import ActionSpace

def dataframe_to_replaybuffer(df, obs_cols, action_cols, reward_col,
                              time_col="timestep_dt", id_col="icustayid"):
    
    df = df.sort_values([id_col, time_col])

    episodes = []
    for stay_id, g in df.groupby(id_col, sort=False):
        obs  = g[obs_cols].to_numpy(dtype=np.float32)
        acts = g[action_cols].to_numpy(dtype=np.float32)    #  (T, 2)
        rews = g[reward_col].to_numpy(dtype=np.float32)

        # terminals         = np.zeros(len(g), bool)
        # terminals[-1]     = True

        ep = Episode(
            observations=obs,
            actions=acts,
            rewards=rews,
            terminated=True,
        )
        episodes.append(ep)

    buf = ReplayBuffer(
        buffer=FIFOBuffer(limit=sum(len(ep) for ep in episodes)),
        episodes=episodes,
        action_space=ActionSpace.CONTINUOUS,
        action_size=2,
    )   # action_size=2 is automatically recorded :contentReference[oaicite:1]{index=1}
    return buf

sepsis_continous_buffer = dataframe_to_replaybuffer(sepsis_fast_padded,observation_columns,action_cols=["output_step", "median_dose_vaso"],reward_col="SOFA")

/home/julian/miniconda3/envs/d3rlpy_dev_requirements_py310/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

2025-08-08 17:34.21 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('float32')], shape=[(2,)]) observation_signature=Signature(dtype=[dtype('float32')], shape=[(48,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[()])

In [42]:
import gymnasium as gym
import d3rlpy
import argparse

from d3rlpy.logging import UnifiedFileAdapterFactory

dt = d3rlpy.algos.DecisionTransformerConfig(
    batch_size=64,
    learning_rate=1e-4,
    optim_factory=d3rlpy.optimizers.AdamWFactory(
        weight_decay=1e-4,
        clip_grad_norm=0.25,
        lr_scheduler_factory=d3rlpy.optimizers.WarmupSchedulerFactory(
            warmup_steps=100#10000
        ),
    ),
    encoder_factory=d3rlpy.models.VectorEncoderFactory(
        [128],
        exclude_last_activation=True,
    ),
    observation_scaler=d3rlpy.preprocessing.StandardObservationScaler(),
    reward_scaler=d3rlpy.preprocessing.MultiplyRewardScaler(0.001),
    position_encoding_type=d3rlpy.PositionEncodingType.SIMPLE,
    context_size=20,
    num_heads=1,
    num_layers=3,
    max_timestep=1000,
    compile_graph=False,
).create(device="cpu")

dt.fit(
    sepsis_continous_buffer,
    n_steps=100,#100000,
    n_steps_per_epoch=10,#1000,
    save_interval=10,
    eval_env=None,
    eval_target_return=0,
    experiment_name=f"DT_Sepsis_continous",
    n_trials=10,
    eval_gaps=1,
    logger_adapter=UnifiedFileAdapterFactory(),
)

2025-08-08 17:34.23 [info     ] dataset info                   dataset_info=DatasetInfo(observation_signature=Signature(dtype=[dtype('float32')], shape=[(48,)]), action_signature=Signature(dtype=[dtype('float32')], shape=[(2,)]), reward_signature=Signature(dtype=[dtype('float32')], shape=[()]), action_space=<ActionSpace.CONTINUOUS: 1>, action_size=2)
2025-08-08 17:34.23 [debug    ] Fitting observation scaler...  observation_scaler=standard

2025-08-08 17:34.29 [debug    ] Building models...
2025-08-08 17:34.35 [debug    ] Models have been built.
2025-08-08 17:34.35 [info     ] Directory is created at d3rlpy_logs/DT_Sepsis_continous_20250808173435
2025-08-08 17:34.35 [info     ] Parameters                     params={'observation_shape': [48], 'action_size': 2, 'config': {'type': 'decision_transformer', 'params': {'batch_size': 64, 'gamma': 0.99, 'observation_scaler': {'type': 'standard', 'params': {'mean': [13.241417404605107, 86.95038703104198, 117.93140155582806, 58.14843013453039, 78.30227874980267, 20.111170855857242, 36.974736302796224, 38.86798875599139, 0.3887144117332443, 4.10113849750285, 138.3659027351623, 103.80038250482191, 144.08484744474373, 1.5490189233010743, 2.072428865181718, 8.306683267636338, 10.054064459023113, 12.58980437770256, 201.98339564126564, 94.04552861506731, 1212.113380126821, 7.399144382589788, 2.2343496650168397, 120.181240815314, 43.80585572189684, 357.07879507098977, 45.88958056582875, 96.64912477875714, 200.26754007324092, 1.4774202536629641, 153.49018129980055, 160.4089989190832, 19.996237938938698, 41.82301071295801, 357.07879364147186, 1.8652378702910581, 0.5847036201445392, 0.6602603430600992, 0.4223273281808328, 0.772826080564828, 0.6644942009867241, 65.2793326969479, 0.43939408788783413, 82.76095067547728, 0.32049716468727274, 0.024270399424444908, 0.3315620387594012, 34970073.555539005], 'std': [3.229496010926186, 17.96986087031182, 19.4347284905385, 14.21089368911653, 13.273846203679183, 5.062358605690823, 3.6935080471906376, 17.467664301950492, 0.17463423018690394, 0.5897636386879312, 5.6728673503447, 6.843795290471916, 56.09236885985333, 0.837979696984529, 0.3686436976733505, 0.7559078444618383, 1.9621226968160208, 9.244649501417925, 115.78525128982338, 7034.290541538938, 32770.09534406846, 0.07059914134812038, 1.781079443803743, 98.08689686410052, 12.975031163550078, 352.36676014260564, 4553.819153581534, 2.6814902335094293, 12733.004722989564, 1.5010882018910352, 564.4450376760336, 573.1529179488897, 4200.080337286036, 6348.8554796608005, 352.36674664335146, 1.3370757891025273, 0.9045043859408263, 1.1375656952227495, 0.72385502250103, 1.1764499265437294, 0.9737382803007636, 16.231479950958423, 0.4963133318952844, 24.093795364994666, 0.4666676891693857, 0.14711151417383211, 0.47077452481323956, 2896865.393305528], 'eps': 0.001}}, 'action_scaler': {'type': 'none', 'params': {}}, 'reward_scaler': {'type': 'multiply', 'params': {'multiplier': 0.001}}, 'compile_graph': False, 'context_size': 20, 'max_timestep': 1000, 'learning_rate': 0.0001, 'encoder_factory': {'type': 'vector', 'params': {'hidden_units': [128], 'activation': 'relu', 'use_batch_norm': False, 'use_layer_norm': False, 'dropout_rate': None, 'exclude_last_activation': True, 'last_activation': None}}, 'optim_factory': {'type': 'adam_w', 'params': {'clip_grad_norm': 0.25, 'lr_scheduler_factory': {'type': 'warmup', 'params': {'warmup_steps': 100}}, 'betas': [0.9, 0.999], 'eps': 1e-08, 'weight_decay': 0.0001, 'amsgrad': False}}, 'num_heads': 1, 'num_layers': 3, 'attn_dropout': 0.1, 'resid_dropout': 0.1, 'embed_dropout': 0.1, 'activation_type': 'relu', 'position_encoding_type': <PositionEncodingType.SIMPLE: 'simple'>}}}

Epoch 1/10: 100%|██████████| 10/10 [00:04<00:00,  2.02it/s, loss=nan]

2025-08-08 17:34.40 [info     ] DT_Sepsis_continous_20250808173435: epoch=1 step=10 epoch=1 metrics={'time_sample_batch': 0.019104933738708495, 'time_algorithm_update': 0.4717341661453247, 'loss': nan, 'time_step': 0.4912107944488525} step=10

Epoch 2/10: 100%|██████████| 10/10 [00:04<00:00,  2.27it/s, loss=nan]

2025-08-08 17:34.45 [info     ] DT_Sepsis_continous_20250808173435: epoch=2 step=20 epoch=2 metrics={'time_sample_batch': 0.02015690803527832, 'time_algorithm_update': 0.4174391269683838, 'loss': nan, 'time_step': 0.4380562543869019} step=20

Epoch 3/10: 100%|██████████| 10/10 [00:04<00:00,  2.17it/s, loss=nan]

2025-08-08 17:34.49 [info     ] DT_Sepsis_continous_20250808173435: epoch=3 step=30 epoch=3 metrics={'time_sample_batch': 0.0211057186126709, 'time_algorithm_update': 0.43560240268707273, 'loss': nan, 'time_step': 0.45713980197906495} step=30

Epoch 4/10: 100%|██████████| 10/10 [00:04<00:00,  2.08it/s, loss=nan]

2025-08-08 17:34.54 [info     ] DT_Sepsis_continous_20250808173435: epoch=4 step=40 epoch=4 metrics={'time_sample_batch': 0.019070959091186522, 'time_algorithm_update': 0.4588464260101318, 'loss': nan, 'time_step': 0.4783478736877441} step=40

Epoch 5/10: 100%|██████████| 10/10 [00:04<00:00,  2.15it/s, loss=nan]

2025-08-08 17:34.59 [info     ] DT_Sepsis_continous_20250808173435: epoch=5 step=50 epoch=5 metrics={'time_sample_batch': 0.020250725746154784, 'time_algorithm_update': 0.4399385929107666, 'loss': nan, 'time_step': 0.46059470176696776} step=50

Epoch 6/10: 100%|██████████| 10/10 [00:05<00:00,  1.87it/s, loss=nan]

2025-08-08 17:35.04 [info     ] DT_Sepsis_continous_20250808173435: epoch=6 step=60 epoch=6 metrics={'time_sample_batch': 0.024384069442749023, 'time_algorithm_update': 0.505407166481018, 'loss': nan, 'time_step': 0.530253267288208} step=60

Epoch 7/10: 100%|██████████| 10/10 [00:05<00:00,  1.69it/s, loss=nan]

2025-08-08 17:35.10 [info     ] DT_Sepsis_continous_20250808173435: epoch=7 step=70 epoch=7 metrics={'time_sample_batch': 0.02493891716003418, 'time_algorithm_update': 0.5629398345947265, 'loss': nan, 'time_step': 0.5883183479309082} step=70

Epoch 8/10: 100%|██████████| 10/10 [00:04<00:00,  2.04it/s, loss=nan]

2025-08-08 17:35.15 [info     ] DT_Sepsis_continous_20250808173435: epoch=8 step=80 epoch=8 metrics={'time_sample_batch': 0.020807433128356933, 'time_algorithm_update': 0.4660078525543213, 'loss': nan, 'time_step': 0.4874175310134888} step=80

Epoch 9/10: 100%|██████████| 10/10 [00:05<00:00,  1.98it/s, loss=nan]

2025-08-08 17:35.20 [info     ] DT_Sepsis_continous_20250808173435: epoch=9 step=90 epoch=9 metrics={'time_sample_batch': 0.020227932929992677, 'time_algorithm_update': 0.4811114311218262, 'loss': nan, 'time_step': 0.5017768621444703} step=90

Epoch 10/10: 100%|██████████| 10/10 [00:06<00:00,  1.64it/s, loss=nan]

2025-08-08 17:35.26 [info     ] DT_Sepsis_continous_20250808173435: epoch=10 step=100 epoch=10 metrics={'time_sample_batch': 0.024213790893554688, 'time_algorithm_update': 0.5824483156204223, 'loss': nan, 'time_step': 0.6071269273757934} step=100

In [43]:
sepsis_continous_buffer.dataset_info

DatasetInfo(observation_signature=Signature(dtype=[dtype('float32')], shape=[(48,)]), action_signature=Signature(dtype=[dtype('float32')], shape=[(2,)]), reward_signature=Signature(dtype=[dtype('float32')], shape=[()]), action_space=<ActionSpace.CONTINUOUS: 1>, action_size=2)

In [44]:
sepsis_continous_buffer.sample_transition().action

array([900.,   0.], dtype=float32)

In [45]:
sepsis_continous_buffer.sample_transition().action_signature

Signature(dtype=[dtype('float32')], shape=[(2,)])

In [46]:
import numpy as np
import pandas as pd

def add_action_bin(original_df: pd.DataFrame) -> pd.DataFrame:
    """
    Add a single 'action_bin' column to df by binning fluid_step_ml and
    vaso_rate_mcgkgm into 5 bins each and computing fluid_bin*5 + vaso_bin.
    Intermediate bins aren’t stored in df.
    """
    df = original_df.copy()
    
    fluid_bins = [-np.inf, 0, 50.00, 152.14, 500.00, np.inf]
    vaso_bins  = [-np.inf, 0, 0.08,   0.20,   0.45,   np.inf]
    labels     = [0, 1, 2, 3, 4]

    df['action_bin'] = (
        pd.cut(
            df['output_step'].fillna(0),
            bins=fluid_bins,
            labels=labels,
            right=True
        ).astype('int8') * 5
        + pd.cut(
            df['median_dose_vaso'].fillna(0),
            bins=vaso_bins,
            labels=labels,
            right=True
        ).astype('int8')
    ).astype('int8')
    
    return df

def add_action_bin_np(original_df: pd.DataFrame) -> pd.DataFrame:
    """
    Add a single 'action_bin' column to df by:
      - binning fluid_step_ml into 5 right‐inclusive buckets [0,50,152.14,500]
      - binning vaso_rate_mcgkgm into 5 right‐inclusive buckets [0,0.08,0.20,0.45]
      - computing action_bin = fluid_bin*5 + vaso_bin
    Treats NaN as zero, and result is cast to int8.
    """

    df = original_df.copy()
    # define the positive cut‐points; values ≤0 map to bin 0, then (0,…]→1…4
    f_edges = [0,   50.00, 152.14, 500.00]
    v_edges = [0,    0.08,   0.20,   0.45]

    df['action_bin'] = (
        5 * np.digitize(df['output_step'].fillna(0).values, f_edges, right=True)
        +     np.digitize(df['median_dose_vaso'].fillna(0).values, v_edges, right=True)
    ).astype('int8')

    return df

In [47]:
sepsis_discrete_actions_np = add_action_bin_np(sepsis_fast_padded)
print(sepsis_discrete_actions_np['action_bin'].dtype)  # int8

sepsis_discrete_actions_np["action_bin"].describe()

int8

count    510173.000000
mean         10.044842
std           7.682751
min           0.000000
25%           0.000000
50%          13.000000
75%          15.000000
max          24.000000
Name: action_bin, dtype: float64

pandas

In [48]:

sepsis_discrete_actions = add_action_bin(sepsis_fast_padded)
sepsis_discrete_actions["action_bin"].describe()

count    510173.000000
mean         10.044842
std           7.682751
min           0.000000
25%           0.000000
50%          13.000000
75%          15.000000
max          24.000000
Name: action_bin, dtype: float64

In [49]:
sepsis_discrete_actions_np.equals(sepsis_discrete_actions)

True

In [50]:
sepsis_discrete_actions

,timestep_dt,GCS,HR,SysBP,DiaBP,MeanBP,RR,Temp_C,FiO2_100,FiO2_1,...,icustayid,output_total,output_step,median_dose_vaso,max_dose_vaso,SOFA,timestep,is_padding,delta_hours,action_bin
0,2174-10-04 08:00:00+00:00,15.0,104.2500,119.000,59.0000,79.0000,20.5000,35.5556,36.0000,0.36,...,30000153.0,2180.0,0.0,0.0,0.0,5.0,6.461550e+09,False,NaN,0
1,2174-10-04 12:00:00+00:00,15.0,104.2500,119.000,59.0000,79.0000,20.5000,35.5556,36.0000,0.36,...,30000153.0,0.0,0.0,0.0,0.0,NaN,NaN,True,4.0,0
2,2174-10-04 16:00:00+00:00,11.0,74.0000,119.000,59.0000,79.0000,21.6923,37.8143,46.6667,0.40,...,30000153.0,2180.0,0.0,0.0,0.0,6.0,6.461579e+09,False,4.0,0
3,2136-01-14 12:00:00+00:00,15.0,104.8750,118.375,71.0000,81.0000,20.5000,35.5556,36.0000,0.36,...,30000484.0,0.0,0.0,0.0,0.0,9.0,5.239600e+09,False,NaN,0
4,2136-01-14 16:00:00+00:00,14.0,104.2500,101.000,71.0000,81.0000,20.5000,35.5556,36.0000,0.36,...,30000484.0,260.0,260.0,0.0,0.0,6.0,5.239614e+09,False,4.0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510168,2147-08-26 20:00:00+00:00,15.0,78.4545,103.333,19.8333,53.2273,13.9091,37.6692,40.0000,0.40,...,39999230.0,0.0,0.0,0.0,0.0,NaN,NaN,True,4.0,0
510169,2147-08-27 00:00:00+00:00,15.0,78.4545,103.333,19.8333,53.2273,13.9091,37.6692,40.0000,0.40,...,39999230.0,0.0,0.0,0.0,0.0,NaN,NaN,True,4.0,0
510170,2147-08-27 04:00:00+00:00,15.0,78.4545,103.333,19.8333,53.2273,13.9091,37.6692,40.0000,0.40,...,39999230.0,0.0,0.0,0.0,0.0,3.0,5.606171e+09,False,4.0,0
510171,2158-03-12 12:00:00+00:00,15.0,78.4545,103.333,19.8333,53.2273,13.9091,37.6692,40.0000,0.40,...,39999286.0,1360.0,0.0,0.0,0.0,3.0,5.938840e+09,False,NaN,0
510172,2167-05-04 08:00:00+00:00,15.0,78.4545,103.333,19.8333,53.2273,13.9091,37.6692,40.0000,0.40,...,39999858.0,7875.0,0.0,0.0,0.0,3.0,6.227400e+09,False,NaN,0

In [51]:
import numpy as np
import pandas as pd
from d3rlpy.dataset import Episode, ReplayBuffer, FIFOBuffer 
from d3rlpy.constants import ActionSpace

def dataframe_to_replaybuffer(df, obs_cols, action_cols, reward_col,action_space:ActionSpace,action_size:int,
                              time_col="timestep_dt", id_col="icustayid"):
    
    df = df.sort_values([id_col, time_col])

    episodes = []
    for stay_id, g in df.groupby(id_col, sort=False):
        obs  = g[obs_cols].to_numpy(dtype=np.float32)
        acts = g[action_cols].to_numpy(dtype=np.float32)    #  (T, 2)
        rews = g[reward_col].to_numpy(dtype=np.float32)

        terminals         = np.zeros(len(g), bool)
        terminals[-1]     = True

        ep = Episode(
            observations=obs,
            actions=acts,
            rewards=rews,
            terminated=True,
        )
        episodes.append(ep)

    buf = ReplayBuffer(
        buffer=FIFOBuffer(limit=sum(len(ep) for ep in episodes)),
        episodes=episodes,
        action_space=action_space,
        action_size=action_size,
    )   # action_size=2 is automatically recorded :contentReference[oaicite:1]{index=1}
    return buf

sepsis_discrete_buffer = dataframe_to_replaybuffer(sepsis_discrete_actions,observation_columns,action_cols=["action_bin"],reward_col="SOFA",
                                                    action_space=ActionSpace.DISCRETE,action_size=25)

2025-08-08 17:36.38 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]) observation_signature=Signature(dtype=[dtype('float32')], shape=[(48,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[()])

In [52]:
from d3rlpy.logging import UnifiedFileAdapterFactory

batch_size = 128
context_size = 30

dt = d3rlpy.algos.DiscreteDecisionTransformerConfig(
    batch_size=batch_size,
    context_size=context_size,
    learning_rate=6e-4,
    activation_type="gelu",
    embed_activation_type="tanh",
    # encoder_factory=d3rlpy.models.PixelEncoderFactory(
    #     feature_size=128, exclude_last_activation=True
    # ),  # Nature DQN
    num_heads=8,
    num_layers=6,
    attn_dropout=0.1,
    embed_dropout=0.1,
    optim_factory=d3rlpy.optimizers.GPTAdamWFactory(
        betas=(0.9, 0.95),
        weight_decay=0.1,
        clip_grad_norm=1.0,
    ),
    warmup_tokens=512 * 20,
    final_tokens=2 * 500000 * context_size * 3,
    # observation_scaler=d3rlpy.preprocessing.PixelObservationScaler(),
    max_timestep=200, # TODO
    position_encoding_type=d3rlpy.PositionEncodingType.GLOBAL,
    compile_graph=False,
).create(device="cpu")

dt.fit(
    sepsis_discrete_buffer,
    n_steps=100,#100000,
    n_steps_per_epoch=10,#1000,
    save_interval=10,
    eval_env=None,
    eval_target_return=0,
    experiment_name=f"Discrete_DT_Sepsis",
    n_trials=10,
    eval_gaps=1,
            eval_action_sampler=d3rlpy.algos.SoftmaxTransformerActionSampler(
            temperature=1.0,
        ),
    logger_adapter=UnifiedFileAdapterFactory(),
)

2025-08-08 17:36.39 [info     ] dataset info                   dataset_info=DatasetInfo(observation_signature=Signature(dtype=[dtype('float32')], shape=[(48,)]), action_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), reward_signature=Signature(dtype=[dtype('float32')], shape=[()]), action_space=<ActionSpace.DISCRETE: 2>, action_size=25)
2025-08-08 17:36.39 [debug    ] Building models...
2025-08-08 17:36.40 [debug    ] Models have been built.
2025-08-08 17:36.40 [info     ] Directory is created at d3rlpy_logs/Discrete_DT_Sepsis_20250808173640
2025-08-08 17:36.40 [info     ] Parameters                     params={'observation_shape': [48], 'action_size': 25, 'config': {'type': 'discrete_decision_transformer', 'params': {'batch_size': 128, 'gamma': 0.99, 'observation_scaler': {'type': 'none', 'params': {}}, 'action_scaler': {'type': 'none', 'params': {}}, 'reward_scaler': {'type': 'none', 'params': {}}, 'compile_graph': False, 'context_size': 30, 'max_timestep': 200, 'learning_rate': 0.0006, 'encoder_factory': {'type': 'default', 'params': {'activation': 'relu', 'use_batch_norm': False, 'dropout_rate': None}}, 'optim_factory': {'type': 'gpt_adam_w', 'params': {'clip_grad_norm': 1.0, 'lr_scheduler_factory': {'type': 'none', 'params': {}}, 'betas': [0.9, 0.95], 'eps': 1e-08, 'weight_decay': 0.1, 'amsgrad': False}}, 'num_heads': 8, 'num_layers': 6, 'attn_dropout': 0.1, 'resid_dropout': 0.1, 'embed_dropout': 0.1, 'activation_type': 'gelu', 'embed_activation_type': 'tanh', 'position_encoding_type': <PositionEncodingType.GLOBAL: 'global'>, 'warmup_tokens': 10240, 'final_tokens': 90000000}}}

Epoch 1/10: 100%|██████████| 10/10 [01:02<00:00,  6.22s/it, loss=nan, learning_rate=5.06e-5]

2025-08-08 17:37.42 [info     ] Discrete_DT_Sepsis_20250808173640: epoch=1 step=10 epoch=1 metrics={'time_sample_batch': 0.18551406860351563, 'time_algorithm_update': 6.028761649131775, 'loss': nan, 'learning_rate': 0.00029736914062500005, 'time_step': 6.2145445346832275} step=10

Epoch 2/10: 100%|██████████| 10/10 [01:02<00:00,  6.22s/it, loss=nan, learning_rate=0.0006]

2025-08-08 17:38.44 [info     ] Discrete_DT_Sepsis_20250808173640: epoch=2 step=20 epoch=2 metrics={'time_sample_batch': 0.18638460636138915, 'time_algorithm_update': 6.028962445259094, 'loss': nan, 'learning_rate': 0.0005999999948947979, 'time_step': 6.215614199638367} step=20

Epoch 3/10: 100%|██████████| 10/10 [01:02<00:00,  6.25s/it, loss=nan, learning_rate=0.0006]

2025-08-08 17:39.46 [info     ] Discrete_DT_Sepsis_20250808173640: epoch=3 step=30 epoch=3 metrics={'time_sample_batch': 0.25474350452423095, 'time_algorithm_update': 5.989447569847107, 'loss': nan, 'learning_rate': 0.000599999962079206, 'time_step': 6.244485664367676} step=30

Epoch 4/10: 100%|██████████| 10/10 [01:03<00:00,  6.31s/it, loss=nan, learning_rate=0.0006]

2025-08-08 17:40.50 [info     ] Discrete_DT_Sepsis_20250808173640: epoch=4 step=40 epoch=4 metrics={'time_sample_batch': 0.2505993127822876, 'time_algorithm_update': 6.057239627838134, 'loss': nan, 'learning_rate': 0.000599999895159323, 'time_step': 6.308132648468018} step=40

Epoch 5/10: 100%|██████████| 10/10 [01:02<00:00,  6.26s/it, loss=nan, learning_rate=0.0006]

2025-08-08 17:41.52 [info     ] Discrete_DT_Sepsis_20250808173640: epoch=5 step=50 epoch=5 metrics={'time_sample_batch': 0.309636664390564, 'time_algorithm_update': 5.95141978263855, 'loss': nan, 'learning_rate': 0.000599999797128868, 'time_step': 6.26134672164917} step=50

Epoch 6/10: 100%|██████████| 10/10 [01:02<00:00,  6.26s/it, loss=nan, learning_rate=0.0006]

2025-08-08 17:42.55 [info     ] Discrete_DT_Sepsis_20250808173640: epoch=6 step=60 epoch=6 metrics={'time_sample_batch': 0.24721593856811525, 'time_algorithm_update': 6.0078617334365845, 'loss': nan, 'learning_rate': 0.0005999996672838871, 'time_step': 6.255343389511109} step=60

Epoch 7/10: 100%|██████████| 10/10 [01:01<00:00,  6.14s/it, loss=nan, learning_rate=0.0006]

2025-08-08 17:43.56 [info     ] Discrete_DT_Sepsis_20250808173640: epoch=7 step=70 epoch=7 metrics={'time_sample_batch': 0.11968271732330323, 'time_algorithm_update': 6.014172697067261, 'loss': nan, 'learning_rate': 0.0005999994979371967, 'time_step': 6.134149551391602} step=70

Epoch 8/10: 100%|██████████| 10/10 [6:01:08<00:00, 2166.86s/it, loss=nan, learning_rate=0.0006]

2025-08-08 23:45.05 [info     ] Discrete_DT_Sepsis_20250808173640: epoch=8 step=80 epoch=8 metrics={'time_sample_batch': 0.2086634397506714, 'time_algorithm_update': 2166.6446426391603, 'loss': nan, 'learning_rate': 0.0005999992941248683, 'time_step': 2166.8535861492155} step=80

Epoch 9/10: 100%|██████████| 10/10 [00:56<00:00,  5.65s/it, loss=nan, learning_rate=0.0006]

2025-08-08 23:46.01 [info     ] Discrete_DT_Sepsis_20250808173640: epoch=9 step=90 epoch=9 metrics={'time_sample_batch': 0.2503532409667969, 'time_algorithm_update': 5.39777946472168, 'loss': nan, 'learning_rate': 0.0005999990637570559, 'time_step': 5.64843475818634} step=90

Epoch 10/10: 100%|██████████| 10/10 [00:58<00:00,  5.80s/it, loss=nan, learning_rate=0.0006]

2025-08-08 23:46.59 [info     ] Discrete_DT_Sepsis_20250808173640: epoch=10 step=100 epoch=10 metrics={'time_sample_batch': 0.25820112228393555, 'time_algorithm_update': 5.543847846984863, 'loss': nan, 'learning_rate': 0.0005999988023091924, 'time_step': 5.802292346954346} step=100

In [53]:
from typing import Iterator
import numpy as np
from d3rlpy.dataset import EpisodeBase, TrajectoryMiniBatch
from d3rlpy.dataset.components import PartialTrajectory

def _compute_episode_targeted_rtg(
    rewards: np.ndarray,     # (T, 1) float32
    target_return: float,
    gamma: float = 1.0,
) -> np.ndarray:
    """Compute global targeted RTG G_t for the entire episode.
       Recurrence:
         G_0 = target_return
         G_{t+1} = (G_t - r_t) / gamma
       If gamma == 1.0, this is just cumulative subtraction.
    """
    T = rewards.shape[0]
    G = np.zeros((T, 1), dtype=np.float32)
    g = float(target_return)
    for t in range(T):
        G[t, 0] = g
        if t < T - 1:
            if gamma == 1.0:
                g = g - float(rewards[t, 0])
            else:
                g = (g - float(rewards[t, 0])) / gamma
    return G

def make_targeted_trajectory_batches_global(
    episode: EpisodeBase,
    window_size: int,
    target_return: float,
    gamma: float = 1.0,
) -> Iterator[TrajectoryMiniBatch]:
    """
    Yield TrajectoryMiniBatch windows where returns_to_go come from a SINGLE
    episode-global targeted RTG sequence G (no per-window reset).
    - Left-pads each window to `window_size`.
    - Masks valid steps (1.0) and padding (0.0).
    - Keeps temporal order identical to the episode.
    """
    # assumes ndarray observations; if you have tuple observations, pad each element separately
    assert isinstance(episode.observations, np.ndarray), "Tuple obs not handled here."

    T = episode.transition_count
    n_batches = T // window_size + (1 if T % window_size != 0 else 0)

    obs_full  = episode.observations.astype(np.float32)                    # (T, ...)
    acts_full = episode.actions.astype(np.float32)                         # (T, ...)
    rews_full = episode.rewards.reshape(-1, 1).astype(np.float32)          # (T, 1)
    terms_full = np.zeros((T, 1), dtype=np.float32)
    terms_full[-1, 0] = float(episode.terminated)

    # compute episode-global G once
    G_full = _compute_episode_targeted_rtg(rews_full, target_return, gamma)  # (T,1)

    for i in range(n_batches):
        head = i * window_size
        tail = min(head + window_size, T)

        obs   = obs_full[head:tail]
        acts  = acts_full[head:tail]
        rews  = rews_full[head:tail]
        terms = terms_full[head:tail]
        rtg   = G_full[head:tail]  # <- global targeted RTG slice

        L = tail - head
        pad = window_size - L

        def _pad_left(x: np.ndarray) -> np.ndarray:
            if pad == 0:
                return x
            return np.concatenate([np.zeros((pad,) + x.shape[1:], dtype=np.float32), x], axis=0)

        observations   = _pad_left(obs)
        actions        = _pad_left(acts)
        rewards        = _pad_left(rews)
        returns_to_go  = _pad_left(rtg)
        terminals      = _pad_left(terms)

        timesteps = np.arange(window_size, dtype=np.float32)
        masks = np.zeros((window_size,), dtype=np.float32)
        masks[-L:] = 1.0

        partial = PartialTrajectory(
            observations=observations,
            actions=actions,
            rewards=rewards,
            returns_to_go=returns_to_go,
            terminals=terminals,
            timesteps=timesteps,
            masks=masks,
            length=window_size,
        )
        yield TrajectoryMiniBatch.from_partial_trajectories([partial])

In [54]:
sepsis_continous_buffer._episodes

AttributeError: 'ReplayBuffer' object has no attribute '_episodes'

In [ ]:
ReplayBuffer.episodes

In [1]:
from mopo.algo import MOPO

ImportError: cannot import name 'MOPO' from 'mopo.algo' (unknown location)

In [1]:
import mopo.common as common
from mopo.algo.mopo import MOPO

ModuleNotFoundError: No module named 'common'

In [3]:
from mopo.algo.sac import SACPolicy

In [5]:
from mopo.models.transition_model import TransitionModel